2017-08-26 12:00:16,799 : Machine : Mission Pinball Framework Core Engine v0.33.33
2017-08-26 12:00:16,799 : Machine : Command line arguments: {'pause': False, 'force_assets_load': False, 'no_load_cache': False, 'configfile': ['config'], 'logfile': 'logs\\2017-08-26-12-00-16-mpf-MSI.log', 'force_platform': None, 'mpfconfigfile': 'c:\\python34\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'mc_file_name': None, 'consoleloglevel': 20, 'create_config_cache': True, 'bcp': True, 'syslog_address': None, 'loglevel': 11}
2017-08-26 12:00:16,799 : Machine : MPF path: c:\python34\lib\site-packages\mpf
2017-08-26 12:00:16,799 : Machine : Machine path: C:\Users\Jim\Documents\Git\Escape_Pinball\monitor
2017-08-26 12:00:16,800 : Machine : Platform: win32
2017-08-26 12:00:16,800 : Machine : Python executable location: c:\python34\python.exe
2017-08-26 12:00:16,800 : Machine : Python version: 3.4.4 (64-bit)
2017-08-26 12:00:17,065 : Machine : Loading config from original files
2017-08-26 12:00:17,140 : Machine : Machine config file #1: C:\Users\Jim\Documents\Git\Escape_Pinball\monitor\config\config
2017-08-26 12:00:17,141 : root : Could not find file C:\Users\Jim\Documents\Git\Escape_Pinball\monitor\config\config
Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\core\file_manager.py", line 147, in load
    file = FileManager.locate_file(filename)
  File "c:\python34\lib\site-packages\mpf\core\file_manager.py", line 120, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: C:\Users\Jim\Documents\Git\Escape_Pinball\monitor\config\config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python34\lib\site-packages\mpf\commands\game.py", line 181, in __init__
    MachineController(mpf_path, machine_path, vars(args)).run()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 96, in __init__
    self._load_config()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 414, in _load_config
    self._load_config_from_files()
  File "c:\python34\lib\site-packages\mpf\core\machine.py", line 434, in _load_config_from_files
    config_type='machine'))
  File "c:\python34\lib\site-packages\mpf\core\config_processor.py", line 24, in load_config_file
    config = FileManager.load(filename, verify_version, halt_on_error)
  File "c:\python34\lib\site-packages\mpf\core\file_manager.py", line 150, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file C:\Users\Jim\Documents\Git\Escape_Pinball\monitor\config\config
