2018-05-07 13:20:06,797 : INFO : Machine : Mission Pinball Framework Core Engine v0.50.4
2018-05-07 13:20:06,797 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'mpfconfigfile': 'c:\\python36\\lib\\site-packages\\mpf\\mpfconfig.yaml', 'force_assets_load': False, 'logfile': 'logs\\2018-05-07-13-20-06-mpf-LT-5CG54443QZ.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None}
2018-05-07 13:20:06,797 : INFO : Machine : MPF path: c:\python36\lib\site-packages\mpf
2018-05-07 13:20:06,797 : INFO : Machine : Machine path: C:\Users\104379\Documents\Git\Escape_Pinball\monitor
2018-05-07 13:20:06,797 : INFO : Machine : Platform: win32
2018-05-07 13:20:06,797 : INFO : Machine : Python executable location: c:\python36\python.exe
2018-05-07 13:20:06,797 : INFO : Machine : Python version: 3.6.4 (64-bit)
2018-05-07 13:20:07,057 : INFO : Machine : Machine config file #1: config.yaml
2018-05-07 13:20:07,067 : WARNING : ConfigProcessor : Cache file not found: C:\Users\104379\AppData\Local\Temp\83ab2a111064720971b2a41081477f36.mpf_cache
2018-05-07 13:20:07,067 : INFO : ConfigProcessor : Loading config from file c:\python36\lib\site-packages\mpf\mpfconfig.yaml.
2018-05-07 13:20:07,117 : INFO : ConfigProcessor : Loading config: c:\python36\lib\site-packages\mpf\mpfconfig.yaml
2018-05-07 13:20:07,117 : INFO : ConfigProcessor : Loading config from file C:\Users\104379\Documents\Git\Escape_Pinball\monitor\config\config.yaml.
2018-05-07 13:20:07,249 : ERROR : root : Could not find file C:\Users\104379\Documents\Git\Escape_Pinball\monitor\config\config.yaml
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\mpf\core\file_manager.py", line 135, in load
    file = FileManager.locate_file(filename)
  File "c:\python36\lib\site-packages\mpf\core\file_manager.py", line 108, in locate_file
    raise FileNotFoundError("File not found: {}".format(filename))
FileNotFoundError: File not found: C:\Users\104379\Documents\Git\Escape_Pinball\monitor\config\config.yaml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\mpf\commands\game.py", line 208, in __init__
    MachineController(mpf_path, machine_path, vars(self.args)).run()
  File "c:\python36\lib\site-packages\mpf\core\machine.py", line 158, in __init__
    self._load_config()
  File "c:\python36\lib\site-packages\mpf\core\machine.py", line 427, in _load_config
    store_to_cache=self.options['create_config_cache'])
  File "c:\python36\lib\site-packages\mpf\core\config_processor.py", line 111, in load_config_files_with_cache
    ignore_unknown_sections)
  File "c:\python36\lib\site-packages\mpf\core\config_processor.py", line 131, in _load_config_file_and_return_loaded_files
    config = FileManager.load(filename, expected_version_str, True)
  File "c:\python36\lib\site-packages\mpf\core\file_manager.py", line 138, in load
    raise IOError("Could not find file {}".format(filename))
OSError: Could not find file C:\Users\104379\Documents\Git\Escape_Pinball\monitor\config\config.yaml
